[package]
name = "bevy_reparate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.3"}
byteorder = "1.5.0"
bytes = "1.5.0"
env_logger = "0.10.0"
log = "0.4.20"
